### ISSUE TITLE
A couple of additions for the Academic section

### ISSUE THREAD

**Issue by moananddrone** [alecmuffett/real-world-onion-sites#43]
Institutional Repository of academic outputs for the University of West London ('UWL Repository'): https://6dtdxvvrug3v6g6d.onion/

Journal of Radical Librarianship: https://xovxbyhwll3qpfsz.onion/

**Comment by alecmuffett** [comment]
invalid HTTPS certificates.

**Comment by alecmuffett** [comment]
closing as deprecated address.
