### ISSUE TITLE
Add Write.as (writing and publishing platform)

### ISSUE THREAD

**Issue by nitrohorse** [alecmuffett/real-world-onion-sites#49]
Suggestion to add [Write.as](https://write.as/), a "minimalist, privacy-focused,
writing and publishing platform."

http://writeas7pm7rcdqg.onion/ (located in their [privacy policy](https://write.as/privacy))

**Comment by alecmuffett** [comment]
how many people use this?

**Comment by chopin2712** [comment]
I think there are quite a lot people who use this. I saw it many times and it is a popular website in the federated websites. 

According to the page [here](https://writefreely.org/) there are over 100 000 blogs on write.as

**Comment by davidkenny** [comment]
All of their links return a 404:
http://writeas7pm7rcdqg.onion/login
http://writeas7pm7rcdqg.onion/new
http://writeas7pm7rcdqg.onion/start
http://writeas7pm7rcdqg.onion/give
http://writeas7pm7rcdqg.onion/newyear

**Comment by alecmuffett** [comment]
closing as deprecated address.
