### ISSUE TITLE
Two suggestions (Mullvad and ProtonMail)

### ISSUE THREAD

**Issue by maique** [alecmuffett/real-world-onion-sites#53]
Mullvad VPN
http://xcln5hkbriyklr6n.onion/

ProtonMail
https://protonirockerxow.onion/

**Comment by bentley** [comment]
Since ProtonMail has been added to the list and Mullvad has its own issue (#47), this issue can be closed.

**Comment by alecmuffett** [comment]
closing as deprecated address.
