### ISSUE TITLE
Add PrivacyTools.io

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [alecmuffett/real-world-onion-sites#54]
> ### [PrivacyTools](http://privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion) 🔧
> *PrivacyTools provides services, tools and knowledge to protect your privacy against global mass surveillance.*
> * link: [http://privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion](http://privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion)
> * plain: `http://privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion`
> * proof: [link](https://write.privacytools.io/jonah/tor-on-privacytools-io)
> * check: <span title="attempts=1 code=200 exit=0 time=2020-01-13 03:40:17+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-12 12:15:15+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-12 00:15:33+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-11 20:49:18+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-11 08:49:26+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-10 17:26:17+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-10 05:59:22+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-09 13:57:22+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-08 22:32:26+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-08 10:32:23+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-07 19:06:22+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-07 07:06:20+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-06 15:40:19+00:00">:white_check_mark:</span><span title="attempts=1 code=200 exit=0 time=2020-01-06 03:40:18+00:00">:white_check_mark:</span>

I was gonna create a pull request of ReadMe.md before I see the warning, stipulating to not push edit on this file.
Of course, as the website status is automatically generated, results of the shown status could differ.

**Comment by alecmuffett** [comment]
maybe.  we'll see how it develops.
