### ISSUE TITLE
Add torproject.org onions

### ISSUE THREAD

**Issue by qbi** [alecmuffett/real-world-onion-sites#56]
The Tor Project maintains several Onion Services for its sub domains. You can find a list at https://onion.torproject.org/
I'll suggest adding those URLs.

**Comment by alecmuffett** [comment]
Politely declined - at the moment where an organisation runs 2+ onion addresses for closely related services that do not reflect distinct languages /  national interests, I am posting a link to an index of their  onions. Examples: Riseup, Systemli, TorProject, ...

**Comment by alecmuffett** [comment]
I shall update the README

**Comment by alecmuffett** [comment]
fixed, thanks
