### ISSUE TITLE
ctrl.blog

### ISSUE THREAD

**Issue by DandelionSprout** [alecmuffett/real-world-onion-sites#60]
As per https://www.ctrl.blog/entry/ctrlblog-onion-mirror.html. The site is a reasonably popular and well-written blog.

Onion: http://v65ngaoj2nyaiq2ltf4uzota254gnasarrkuj4aqndi2bb5lw6frt3ad.onion
Non-Onion: https://www.ctrl.blog/

**Comment by alecmuffett** [comment]
done, thanks.
