### ISSUE TITLE
Facebooks v3 Onion

### ISSUE THREAD

**Issue by CJFWeatherhead** [alecmuffett/real-world-onion-sites#63]
I believe its : https://www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion/ 

DigiCert EV can be found here: https://crt.sh/?id=4508700997

This is more a placeholder until they "officially" announce it

**Comment by CJFWeatherhead** [comment]
This has now been officially announced by Facebook:

https://www.facebook.com/facebookcorewwwi/posts/3727741430665883

and here: https://www.facebook.com/onion-service

**Comment by alecmuffett** [comment]
done, thanks
