### ISSUE TITLE
Privacy International (v2 -> v3)

### ISSUE THREAD

**Issue by CJFWeatherhead** [alecmuffett/real-world-onion-sites#64]
We have updated our .onion, we plan to continue running both in tandem until the certificate of the v2 expires.

Our new onion is:

privacy2ws3ora5p4qpzptqr32qm54gf5ifyzvo5bhl7bb254c6nbiyd.onion (Verified by EV SSL)

Should be online by 21 May 2021

Best Regards,
Chris

**Comment by alecmuffett** [comment]
done, thanks.
