### ISSUE TITLE
Add "The New York Times" v3 address (list only has v2 legacy)

### ISSUE THREAD

**Issue by CubeBag** [alecmuffett/real-world-onion-sites#69]
nytimesn7cgmftshazwhfgzm37qxb44r64ytbb2dj3x62d2lljsciiyd

Proof: The address can be found from the New York Times clearnet site's Onion-Location header. The new v3 URL should take precedence over the v2 URL which currently exists in the list.

**Comment by alecmuffett** [comment]
fixed thanks!
