### ISSUE TITLE
archive.today v3 update

### ISSUE THREAD

**Issue by bdd** [alecmuffett/real-world-onion-sites#70]
Archive.today is currently listed among the sites with legacy addresses. Looks like they did announce the v3 address Aug 11, 2021 on their blog.

While you're there, you may want to drop the mention of "archive.is", as archive.today is their canonical clear net address and name.

v3 address: http://archiveiya74codqgiixo33q62qlrqtkgmcitqx5u2oeqnmn5bpcbiyd.onion
proof: https://blog.archive.today/post/659192060146024448/will-archivecaslytoskonion-be-upgraded-to-onion

**Comment by alecmuffett** [comment]
fixed thanks!
