### ISSUE TITLE
nytimes proof URL only mentions the legacy address

### ISSUE THREAD

**Issue by bdd** [alecmuffett/real-world-onion-sites#71]
Maybe NYTimes proof should be update to SSL. Currently linked URL is from Oct 2017, and only mentions the legacy v2 address.

Clear Net address in the Onion Cert: https://crt.sh/?id=5386738107

...or Onion-Location header:
```
% curl -sI https://nytimes.com/ | grep -i onion-location:
onion-location: https://www.nytimesn7cgmftshazwhfgzm37qxb44r64ytbb2dj3x62d2lljsciiyd.onion/
```

**Comment by alecmuffett** [comment]
fixed, thanks!
