### ISSUE TITLE
Add tech.michaelaltfield.net (disclosure: it's my tech blog)

### ISSUE THREAD

**Issue by maltfield** [alecmuffett/real-world-onion-sites#76]
This is a request to add my decently-popular technology blog to this list.

Clearnet: https://tech.michaelaltfield.net/
Darknet: https://tech.michaelahgu3sqef5yz3u242nok2uczduq5oxqfkwq646tvjhdnl35id.onion

Proof: https://tech.michaelaltfield.net/2021/01/15/onion/

**Comment by maltfield** [comment]
> no sites for tech with less than (arbitrary) 10,000 users

I'm not quite sure what this means for blogs. I certainly don't have but a few registered "users" on my wordpress site..

And there's no "per unit of time" in the quote above. is it per day? Is it per month? per year?

I can tell you that I have less than 10,000 unique visitors per month. I have more than 10,000 unique visitors per year.

**Comment by alecmuffett** [comment]
in progress

**Comment by maltfield** [comment]
thanks! It looks good, so I'll close this :)
