### ISSUE TITLE
Twitter Tor Proof

### ISSUE THREAD

**Issue by railworks2** [alecmuffett/real-world-onion-sites#83]
https://twitter.com/torproject/status/1501285555639705600
https://help.twitter.com/en/using-twitter/twitter-supported-browsers

Both now show that https://twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion/ is now the official Tor address for Twitter.

**Comment by alecmuffett** [comment]
i've already got that, but thanks.
